name: microgoals
description: "A focused goal-tracking app that helps users stay focused on meaningful objectives."
publish_to: 'none'

version: 1.0.3+4

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # State Management
  flutter_riverpod: ^2.4.9
  
  # Navigation
  go_router: ^12.1.3
  
  # Database & Storage
  sqflite: ^2.3.0
  shared_preferences: ^2.2.2
  path_provider: ^2.1.1
  
  # UI & Assets
  google_fonts: ^6.1.0
  fl_chart: ^0.66.0
  lottie: ^3.1.0
  intl: ^0.19.0
  
  # Features
  in_app_purchase: ^3.1.11
  path: ^1.9.1
  share_plus: ^10.1.2
  file_picker: ^8.1.4
  package_info_plus: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  sqflite_common_ffi: ^2.3.2
  flutter_launcher_icons: ^0.14.2

flutter:
  uses-material-design: true

  assets:
    - assets/

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/MicroGoalsIcon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/MicroGoalsIcon.png"
